upstream web-backend {
    server 172.23.32.205:18080 weight=1 max_fails=3 fail_timeout=20s;
}

server {
    listen 13001;
    server_name  localhost;

    access_log /data/nginx_log/aivideo-access.log main;
    error_log /data/nginx_log/aivideo-error.log error;

    location ^~ /video {
        root /data/aivideo-web;
        index index.html index.htm index.php;
    }
    location ^~ /react {
        root /data/aivideo-web;
        index index.html index.htm index.php;
    }
    location ^~ /datav {
        root /data/aivideo-web;
        index index.html index.htm index.php;
    }
    location ^~ /ai/api/ {
        include vhosts/proxy.conf;
        proxy_pass http://web-backend;
   }
   location ^~ /api/ {
        include vhosts/proxy.conf;
        proxy_pass http://web-backend;
   }
   location ^~ /v1/ {
        include vhosts/proxy.conf;
        proxy_pass http://web-backend;
   }
    location ^~ /cockpit/api/ {
        include vhosts/proxy.conf;
        proxy_pass http://web-backend;
   }
}
