import createClient, { ClientOptions, Middleware } from "openapi-fetch";
import packageJson from '../package.json';
import type { paths } from "./openapi/schema.d.ts"; // generated by openapi-typescript
import { getAccessToken } from "./token-utils.ts";

const UNPROTECTED_ROUTES = ["/v1/public/"];

export const packageInfo = {
    name: packageJson.name,
    version: packageJson.version
}

function emitLogin(){
    window.top?.dispatchEvent(new CustomEvent("unauthorized"))
}

const authMiddleware: Middleware = {
    async onRequest({ schemaPath, request }) {
        if (UNPROTECTED_ROUTES.some((pathname) => schemaPath.startsWith(pathname))) {
            return undefined; // don’t modify request for certain paths
        }
        const token = await getAccessToken()
        if (token) {
            // set "foo" header
            const headers = request.headers
            headers.set("x-access-token", token)
            headers.set("access-token", token)
            return request;
        }else{
            // emitLogin()
            return undefined
        }
    },
    async onResponse({response}){
        const status = response.status
        if(status === 401){
            emitLogin()
        }
    }
};


export function getApiClient(clientOptions?: ClientOptions) {
    const baseUrl = "http://8.138.1.223:18080";
    const client = createClient<paths>({baseUrl, ...clientOptions });
    client.use(authMiddleware)
    return client;
}