import createClient, { ClientOptions, Middleware } from "openapi-fetch";
import packageJson from '../package.json';
import type { paths } from "./openapi/schema.d.ts"; // generated by openapi-typescript
import { getAccessToken } from "./token-utils.ts";

const UNPROTECTED_ROUTES = ["/v1/public/"];

export const packageInfo = {
    name: packageJson.name,
    version: packageJson.version
}

const authMiddleware: Middleware = {
    async onRequest({ schemaPath, request }) {
        if (UNPROTECTED_ROUTES.some((pathname) => schemaPath.startsWith(pathname))) {
            return undefined; // don’t modify request for certain paths
        }
        const token = await getAccessToken()
        if (token) {
            // set "foo" header
            const headers = request.headers
            headers.set("x-access-token", token)
            headers.set("access-token", token)
            return request;
        }
    }
};
export function getApiClient(clientOptions?: ClientOptions) {
    const client = createClient<paths>({ ...clientOptions });
    client.use(authMiddleware)
    return client;
}