server {
    listen 8055;
    server_name localhost;
    # server_name fyict.cn;
    # ssl_certificate D:/nginx-1.20.2/cert/fyict.cn.crt;
    # ssl_certificate_key D:/nginx-1.20.2/cert/fyict.cn.key;
    # ssl_session_timeout 5m;
    # ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    # ssl_ciphers ALL:!ADH:!EXPORT56:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:!RC4;
    # ssl_prefer_server_ciphers on;

	location / {
	    root /data/aiVideo-web;
        index index.html index.htm;
		try_files $uri $uri/ /index.html;
    }
	location /ai/api/ {
        include    vhosts/proxy.conf;
        proxy_pass http://188.4.89.120:18080;
        #add_header Access-Control-Allow-Origin *;
        #add_header Access-Control-Allow-Methods *;
        #add_header Access-Control-Allow-Headers *;

		#代理后保证cookie传递
		#proxy_cookie_path / /;

    }
}
server {
    listen 8066;
    server_name localhost;
    # server_name fyict.cn;
    # ssl_certificate D:/nginx-1.20.2/cert/fyict.cn.crt;
    # ssl_certificate_key D:/nginx-1.20.2/cert/fyict.cn.key;
    # ssl_session_timeout 5m;
    # ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    # ssl_ciphers ALL:!ADH:!EXPORT56:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:!RC4;
    # ssl_prefer_server_ciphers on;

	location / {
	    root /data/aiVideo-web-react;
        index index.html index.htm;
		try_files $uri $uri/ /index.html;
    }
	location /ai/api/ {
        include    vhosts/proxy.conf;
        proxy_pass http://188.4.89.120:18080;
        #add_header Access-Control-Allow-Origin *;
        #add_header Access-Control-Allow-Methods *;
        #add_header Access-Control-Allow-Headers *;


		#代理后保证cookie传递
		#proxy_cookie_path / /;

    }
}
